### ISSUE TITLE
`REXSushiFarmMarket` Testing and Migration to Typescript

### ISSUE THREAD

**Issue by mikeghen** [Ricochet-Exchange/ricochet-protocol#10]
This issue is about testing and debugging the `REXSushiFarmMarket` contract. The contract is mostly code complete with perhaps a few things missing. The code is untested and needs to be both tested and then anything not working should be debugged.

**Comment by MrSquiggles13** [comment]
After I finish the require testing I wanna give this a shot if that is ok

**Comment by MrSquiggles13** [comment]
@josealonso @rashtrakoff  status on progress?

**Comment by rashtrakoff** [comment]
> @josealonso @rashtrakoff  status on progress?

I am planning to start this today or tomorrow.

**Comment by rashtrakoff** [comment]
> > @josealonso @rashtrakoff  status on progress?
> 
> I am planning to start this today or tomorrow.

@MrSquiggles13 I am not gonna be able to start this on time and instead of squatting, I would like you to take up this issue provided @josealonso is ok with this. Just keep us posted using a thread on the Discord server. If you face issues, I can help you with that.

**Comment by MrSquiggles13** [comment]
@rashtrakoff thats fine by me ill work on it today

**Comment by josealonso** [comment]
> > > @josealonso @rashtrakoff  status on progress?
> > 
> > 
> > I am planning to start this today or tomorrow.
> 
> @MrSquiggles13 I am not gonna be able to start this on time and instead of squatting, I would like you to take up this issue provided @josealonso is ok with this. Just keep us posted using a thread on the Discord server. If you face issues, I can help you with that.

**Comment by josealonso** [comment]
That's fine, @rashtrakoff. I'm sorry I closed the issue for some seconds.

**Comment by mikeghen** [comment]
Im going to close this issue, the sushiswap farm market isn't something we're ready to deploy, it was not a popular service
