### ISSUE TITLE
REX Launchpad Referral Integration

### ISSUE THREAD

**Issue by mikeghen** [Ricochet-Exchange/ricochet-protocol#103]
This task involves integrating the REX Referral system into the REX Launchpad contracts, depends on #102.

**Comment by mikeghen** [comment]
I'm working on this and #102

**Comment by gitChimp88** [comment]
@mikeghen I made a start on the test with this pull request - https://github.com/Ricochet-Exchange/ricochet-protocol/pull/120

**Comment by gitChimp88** [comment]
@mikeghen this pull request is now ready for review - https://github.com/Ricochet-Exchange/ricochet-protocol/pull/120
