### ISSUE TITLE
Use Constants in Deploy Scripts

### ISSUE THREAD

**Issue by mikeghen** [Ricochet-Exchange/ricochet-protocol#108]
This tasks involves replacing all the constants hard coded in the scripts with constants from misc/Constants.ts

**Comment by gitChimp88** [comment]
@mikeghen Can I take this one? first time contributor here!

**Comment by josealonso** [comment]
> @mikeghen Can I take this one? first time contributor here!

Of course, no need to ask. I think this a very good first issue. I created the **Constants.ts** file myself, feel free to ask here or on our discord server. Thanks for contributing !!

**Comment by gitChimp88** [comment]
I have a question, there are some unused variables in the script files, should these variables be added to the constants file and then link them in the script file or should I just delete any unused variables?
Also for variables that are used but are not in the constants file should I add these to the constants file and use them from there?

**Comment by josealonso** [comment]
Sorry, @gitChimp88, I wrote my comment on your PR before reading your questions here. I would ask @mikeghen  those particular questions, because he wrote those contracts. Don't forget to tag him next time.

**Comment by mikeghen** [comment]
@gitChimp88, @josealonso, thanks for this #109

**Comment by mikeghen** [comment]
> @mikeghen Can I take this one? first time contributor here!

yes, thanks! Also submit for a RIC bounty here: https://docs.ricochet.exchange/business/bounty-hunters#completed-a-bounty

**Comment by mikeghen** [comment]
@gitChimp88, I was just taking a look at this issue in the code and it would be great if you could go through and refactor all the constants used in the deploy scripts and put them into Constants.ts too for an additional $250 bounty, lmk if your interested

**Comment by gitChimp88** [comment]
@mikeghen Sure I can get started on that tomorrow! :)

**Comment by mikeghen** [comment]
@gitChimp88 also, I definitely prematurely merged this I just tested this today and I get this error:
```
/Users/mikeghen/Documents/Projects/ricochet-protocol/scripts/deploy-rextwowaymarket.js:1
import { Constants } from '../misc/Constants';
^^^^^^

SyntaxError: Cannot use import statement outside a module
    at wrapSafe (internal/modules/cjs/loader.js:1001:16)
    at Module._compile (internal/modules/cjs/loader.js:1049:27)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)
    at Module.load (internal/modules/cjs/loader.js:950:32)
    at Function.Module._load (internal/modules/cjs/loader.js:790:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:76:12)
    at internal/main/run_main_module.js:17:47
```
did you test to make sure your changes work?

**Comment by mikeghen** [comment]
I'll revert this merge so the deploy scripts work, if you get the deploy scripts running with your changes, let me know

**Comment by josealonso** [comment]
> @gitChimp88 also, I definitely prematurely merged this I just tested this today and I get this error:
> 
> ```
> /Users/mikeghen/Documents/Projects/ricochet-protocol/scripts/deploy-rextwowaymarket.js:1
> import { Constants } from '../misc/Constants';
> ^^^^^^
> 
> SyntaxError: Cannot use import statement outside a module
>     at wrapSafe (internal/modules/cjs/loader.js:1001:16)
>     at Module._compile (internal/modules/cjs/loader.js:1049:27)
>     at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)
>     at Module.load (internal/modules/cjs/loader.js:950:32)
>     at Function.Module._load (internal/modules/cjs/loader.js:790:14)
>     at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:76:12)
>     at internal/main/run_main_module.js:17:47
> ```
> 
> did you test to make sure your changes work?

@mikeghen, all the files must be in Typescript. Otherwise, the **Constants.ts** file will not work. I always try to use Typescript instead of Javascript because programming in a typed language is much faster, at least for me. Why are you still using *Javascript* files ?

**Comment by gitChimp88** [comment]
@mikeghen my bad I must have missed that, I made the changes and the pr is here - https://github.com/Ricochet-Exchange/ricochet-protocol/pull/113
I'm still having some trouble with the deploy scripts (I don't think it's to do with the constants)
This is the error message I get - 
"Error: Returned error: error:0308010C:digital envelope routines::unsupported"

@josealonso I can refactor all scripts to use typescript if that's preferable?

**Comment by josealonso** [comment]
> @mikeghen my bad I must have missed that, I made the changes and the pr is here - #113 I'm still having some trouble with the deploy scripts (I don't think it's to do with the constants) This is the error message I get - "Error: Returned error: error:0308010C:digital envelope routines::unsupported"
> 
> @josealonso I can refactor all scripts to use typescript if that's preferable?
I refactored everything in TS. I'm going to make the PR now.

**Comment by gitChimp88** [comment]
@josealonso okay i just merged it with your changes and fixed the gitignore issues too
