### ISSUE TITLE
`REXMarket` Testing and Debugging

### ISSUE THREAD

**Issue by mikeghen** [Ricochet-Exchange/ricochet-protocol#11]
This issue is about testing and debugging the`REXMarket` contract. The contract is mostly code complete with perhaps a few things missing. The code is untested and needs to be both tested and then anything not working should be debugged.

**Comment by rashtrakoff** [comment]
I will take this one :+1: . If anyone else is interested in doing the same, let me know !

**Comment by josealonso** [comment]
This issue as stated doesn't make sense because the `REXMarket` contract is abstract. @rashtrakoff, @vaibhavgeek, any objections ?
