### ISSUE TITLE
Convert Scripts to Typescript, Use Constants.ts

### ISSUE THREAD

**Issue by mikeghen** [Ricochet-Exchange/ricochet-protocol#114]
Remove the scripts crossed out below, convert the rest to TS, DM me with questions for how to test these scripts, it can be tricky, distribute.js is probably the easiest to test on your own, deploy-rextwowaymarket.js might be harder to test since we use the mainnet forking strategy.
<img width="289" alt="Screen Shot 2022-05-24 at 7 55 42 AM" src="https://user-images.githubusercontent.com/5077880/170029022-6c394118-1ba9-4d0f-b489-9deea18385e8.png">

**Comment by josealonso** [comment]
I didn't run the tests.

**Comment by josealonso** [comment]
I run the tests. Everything is working fine.
