### ISSUE TITLE
Remove `artifacts` from Git

### ISSUE THREAD

**Issue by mikeghen** [Ricochet-Exchange/ricochet-protocol#115]
Somehow the `artifacts` directory has slipped into the git history so PRs keep including a lot of noise from changes to this directory. This issue is to remove the `artifacts` directory from the git history so it no longer gets included in PRs.

**Comment by mikeghen** [comment]
See #113 as an example of a PR that has this included

**Comment by gitChimp88** [comment]
@mikeghen Seeing as it's my pr I can take a look at this one
