### ISSUE TITLE
Typescript errors in test files

### ISSUE THREAD

**Issue by gitChimp88** [Ricochet-Exchange/ricochet-protocol#119]
I'm looking at the tests in typescript and there seem to be a few errors e.g. - 
in REXTwoWayMarket.test.ts
"Type 'Contract' is missing the following properties from type 'TellorPlayground': contractName, addTip, allowance, approve, and 24 more."
Do these need to be addressed? is anyone else seeing these errors?

**Comment by josealonso** [comment]
@gitChimp88, these errors probably have to do with the *artifacts* directory. We are discussing this on our discord group.

**Comment by josealonso** [comment]
I cloned the repo from scratch. I saw that error message when trying to run the tests. I added the test/artifacts directory back and it's now working. @mikeghen, you can close this issue if it's working for you.
