### ISSUE TITLE
REX Super Swap Enhancements

### ISSUE THREAD

**Issue by mikeghen** [Ricochet-Exchange/ricochet-protocol#127]
- [ ] Bring over the REXSuperSwap contract from https://github.com/Ricochet-Exchange/ricochet-super-swap into this repository (Might be challenging since some of Uniswap v2 uses v0.7 and we use v0.8 solc)
- [ ] Write tests for just the REXSuperSwap contracts
- [ ] Improve the swap method of REXSuperSwap, currently I don't think it properly handles:
    - [ ] Native supertoken swaps (i.e. RIC to USDCx)
    - [ ] Decimal precision (i.e. USDC has 6 decimals, WBTC has 8)

Take a look at the `_swap` method from REXTwoWayMarket.sol:
https://github.com/Ricochet-Exchange/ricochet-protocol/blob/v2/contracts/REXTwoWayMarket.sol#L380
There is code in there for solving the native supertoken swap as well as the decimal precision issues

**Comment by gitChimp88** [comment]
@mikeghen I'm currently working on this, should have a pr this week
