### ISSUE TITLE
Install and setup hardhat-solhint

### ISSUE THREAD

**Issue by mikeghen** [Ricochet-Exchange/ricochet-protocol#17]
Install this package so that contributors can run `npx hardhat check`  and this can be part of the continuous integration process, make it a check in github on PRs so unformatted code is physically cant be merged: 
https://hardhat.org/plugins/nomiclabs-hardhat-solhint.html

**Comment by josealonso** [comment]
I'm going to do this task.

**Comment by josealonso** [comment]
I installed the "hardhat-solhint" package. I don't know if it's useful, since "solhint" was already installed. The rules are here: https://github.com/protofire/solhint/blob/master/docs/rules.md. 
I also installed "prettier".

**Comment by josealonso** [comment]
I forgot to close this issue.
