### ISSUE TITLE
Referral System

### ISSUE THREAD

**Issue by mikeghen** [Ricochet-Exchange/ricochet-protocol#3]
This is an affiliate program. Fees paid by streamers will be shared with the affiliate that referred them.

This is used by people like FTX referrals links, something like: https://ricochet.exchange/?affiliateId=1

![a9744597-9631-4629-b710-e7ec8f723d04](https://user-images.githubusercontent.com/5077880/143282798-d477290e-f29c-4cf1-8cdb-c4eb00f8e4be.png)

The 2% fee taken maybe further slip into portions for the affiliates that have referred volume to the app.

**Comment by abstractpoint** [comment]
Front End work is being scoped here: https://github.com/Ricochet-Exchange/ricochet-frontend/issues/145

**Comment by shreyaspapi** [comment]
I am working on it 👆

**Comment by harshitsinghai77** [comment]
I'm working on it with @shreyaspapi

**Comment by harshitsinghai77** [comment]
I think we should close this issue?

**Comment by shreyaspapi** [comment]
> I think we should close this issue?

Still not complete merged to main.

**Comment by mikeghen** [comment]
This is complete, tested it and confirmed working
