### ISSUE TITLE
Best Practices and Audit Fixes (Smart Contracts)

### ISSUE THREAD

**Issue by rashtrakoff** [Ricochet-Exchange/ricochet-protocol#32]
The issue is regarding styling and optimisation of smart contracts. Currently, the contracts aren't following best practices according to out style guide as well as linter. Also in some contracts, modest optimisations can be made such as converting some variables to constants and cutting down on number of parameters passed during initialisation. Further description will be provided in the PR comments regarding the changes made.

**Comment by harshitsinghai77** [comment]
We can add linter and other style practices in the Github Action. This will make sure the best practices are followed every time the PR is merged with the main branch.

**Comment by josealonso** [comment]
@harshitsinghai77, I'm sure @rashtrakoff is doing his best to make sure the solidity code doesn't have any warnings and follows the best practices. I have my own rules in my linter, too. There are a lot of warnings right now. 
But he's still improving and understanding @mikeghen's code. It's a work in progress.

**Comment by rashtrakoff** [comment]
> We can add linter and other style practices in the Github Action. This will make sure the best practices are followed every time the PR is merged with the main branch.

Yes, we actually discussed about this but I think using CI, we can probably only add linter and prettier tasks. Other style practices that I am talking about is a bit more abstract so it really depends on the creator of a contract. I think for CI, having linter and prettier check is enough @harshitsinghai77

**Comment by rashtrakoff** [comment]
This issue has been solved for now (code was pushed to `ida-fees-2` branch). This will be closed once all contracts are ready and final style updates are made.

**Comment by rashtrakoff** [comment]
This issue is tabled for later. Until all contracts are reviewed and stable, this issue will exist.

**Comment by josealonso** [comment]
@rashtrakoff, I assume this will be merge as soon as v.2 contracts are deployed, am I right ? Did you talk to @samirsalem about integrating this tasks in the CI tool ?

**Comment by rashtrakoff** [comment]
> @rashtrakoff, I assume this will be merge as soon as v.2 contracts are deployed, am I right ? Did you talk to @samirsalem about integrating this tasks in the CI tool ?

I guess you are right about merging this after V2 deployment but as the contracts have changed significantly since I created this PR/issue, the contracts need to be revisited. 

Regarding CI, no I haven't but I think it's just the matter of checking for linter errors and warnings.

**Comment by josealonso** [comment]
Retaking this task, right after seeing the test suite have been migrated to **sdk-core** .

**Comment by josealonso** [comment]
The plan is: 
- Make the contracts smaller 
- Use a single contract thanks to the Clone factory pattern 
- In the mid-term, make it upgradeable. 
Before all those steps, having a clean code with no warnings and a comprehensive test suite in sdk-core is very advisable. 
**The scope of this issue is having a clean code and make the contracts smaller** 
```
the contracts need to be made smaller first, right now they're all ~24KB
```

**Comment by mikeghen** [comment]
Closed because of inaction
