### ISSUE TITLE
Test all `require` statements 

### ISSUE THREAD

**Issue by mikeghen** [Ricochet-Exchange/ricochet-protocol#38]
This issue is to add tests so there's coverage testing the positive and negative case for each `require` statement in the protocol. This should be done in all the contracts, but start with `REXMarket` and `REXOneWayMarket` to claim this bounty.

**Comment by josealonso** [comment]
A new contributor called @r5n in discord is working on this.

**Comment by josealonso** [comment]
I temporarily assigned to me only to put an avatar. But @r5n is doing it, not me.

**Comment by MrSquiggles13** [comment]
@r5n dropped this issue I'm going to pick it up

**Comment by MrSquiggles13** [comment]
@josealonso @mikeghen  told me not to do this one for some reason
 
I am willing to pick it back up if its allowed

**Comment by josealonso** [comment]
> @josealonso @mikeghen told me not to do this one for some reason
> 
> I am willing to pick it back up if its allowed

@MrSquiggles13, thanks for letting us know. If you pick it back up, just make sure you have the time to work on it. There's an archived discord thread related to this issue. You might want to reopen it when you will start working on this task.

**Comment by josealonso** [comment]
I just added the *question* label because the existing tests have to be migrated to **sdk-core**. The existing Superfluid's Javascript SDK is deprecated

**Comment by mikeghen** [comment]
Closed because of inaction
