### ISSUE TITLE
Test and Debug Subsidy Output (i.e. output pool where `emissionRate > 0`) 

### ISSUE THREAD

**Issue by mikeghen** [Ricochet-Exchange/ricochet-protocol#45]
To add a subsidy to a REXOneWayMarket, you call `addOutputPool` with `feeRate == 0` and `emissionRate > 0` (see image)

Im fairly confident this is currently working fine since it used most of the code from v1, but it needs to be tested.

<img width="1403" alt="Screen Shot 2022-01-21 at 9 53 12 AM" src="https://user-images.githubusercontent.com/5077880/150547980-7e800c11-2ef6-440f-80b5-bbbf0c848b13.png">

**Comment by MrSquiggles13** [comment]
@vaibhavgeek status update on progress?

**Comment by vaibhavgeek** [comment]
It's almost done, I will be raising the pull request by tomorrow.

**Comment by mikeghen** [comment]
Will just reopen this, lets add a $500 bounty for doing this on the TwoWay market, since you did it once on OneWay this should be less work 🤞

**Comment by josealonso** [comment]
I'm going to do it for the REXTwoWay market.

**Comment by josealonso** [comment]
I'll leave it to @vaibhavgeek

**Comment by vaibhavgeek** [comment]
PR is raised for this issue: https://github.com/Ricochet-Exchange/ricochet-protocol/pull/59
