### ISSUE TITLE
Implement IDA fees and Referral System in `REXTwoWayMarket`

### ISSUE THREAD

**Issue by mikeghen** [Ricochet-Exchange/ricochet-protocol#46]
This task involves implementing the IDA fees (#4) and the referral system (#3) into the `REXTwoWayMarket`. The two way market uses a lot of overrides, so the IDA fee and referral system need to be reimplemented. Use REXMarket's implementation of the IDA fees and referral system as a reference.

**Comment by shreyaspapi** [comment]
Already done by @mikeghen , confirm in discord.
