### ISSUE TITLE
Let customers claim their refund after closing the stream

### ISSUE THREAD

**Issue by mikeghen** [Ricochet-Exchange/ricochet-protocol#49]
- one issue SF indentified in their review is the ERC20 transfer at the stream close, they suggest making it so people would have to claim this in a seperate transaction
- ws thinking a mapping with amount owed, and when theyre closing, it just increments amount owed for that wallet
- then add a `claimRefund` method

**Comment by MrSquiggles13** [comment]
@vaibhavgeek progress on this issue?

**Comment by vaibhavgeek** [comment]
I have understood the details properly, this will be done in the same PR as well.

**Comment by vaibhavgeek** [comment]
This is already completed @mikeghen
