### ISSUE TITLE
Move Swap Methods to a Library

### ISSUE THREAD

**Issue by mikeghen** [Ricochet-Exchange/ricochet-protocol#52]
From discord chat:
I'm thinking we need to have a REXSwapLibrary, these contracts are getting large, I think sushiswap interactions can be cherry-picked out into a library, would you take a look at this? I can make an issue

This would go into the ricochet-protocol repo, we don't need REXSuperSwap exactly, though it would look similar and might have some of the same functionality

It is all the REXMarkets, we have a swap method, which adds a lot to the contract size. If we put it in a library, then use that lib, it'll help reduce the sizes

**Comment by mikeghen** [comment]
What I think works:

```
library REXUniswapV2Adapter {

   function swap(IUniswapV2Router self, amountIn, minAmountOut, ...) {
      // Do REXSuperSwap-style swap
   }

}
```
Then in `REXMarkets`
```
using REXUniswapV2Adapter for IUniswapV2Router;
IUniswapV2Router router;
```
Inside a function in REXMarket:
```
router.swap(....);
```

**Comment by MrSquiggles13** [comment]
On it

**Comment by nikramakrishnan** [comment]
🚧 Work in progress!

**Comment by josealonso** [comment]
@nikramakrishnan, can I close this issue ? I read the discussions on discord, but not sure if more work has to be done. Thanks !!

**Comment by nikramakrishnan** [comment]
#53 should have closed this, but I guess there was some issue. This can be closed.
