### ISSUE TITLE
Refund Unswapped Amounts on Stream Close

### ISSUE THREAD

**Issue by mikeghen** [Ricochet-Exchange/ricochet-protocol#6]
Right now, when a stream is closed, the funds streamed before closing a stream are lost. The best thing to do is refund them the unswapped input tokens.

**Comment by mikeghen** [comment]
This should be implemented in `REXMarket.sol`

**Comment by vaibhavgeek** [comment]
I would like to try this out, @mikeghen

**Comment by rashtrakoff** [comment]
> I would like to try this out, @mikeghen 

How far along are you @vaibhavgeek ? I have this code ready in a hackathon project of mine (dSIP). If you need help, let me know 👍

**Comment by vaibhavgeek** [comment]
@rashtrakoff I am opening a thread on discord regarding the same.

**Comment by rashtrakoff** [comment]
> @rashtrakoff I am opening a thread on discord regarding the same. 

I already did @vaibhavgeek

**Comment by mikeghen** [comment]
I tested this works :+1: nice work all
