### ISSUE TITLE
Streamed interest payments

### ISSUE THREAD

**Issue by mikeghen** [Ricochet-Exchange/ricochet-protocol#62]
Claim this bounty by implementing streaming interest payments.

Borrowers must stream the interest payment on the borrowed funds in real-time. For example:
* Borrow $1000 at 12% APR
* Borrower streams $100/month in interest until they repay

What happens when the borrower doesn’t have enough to stream? On stream closure, if there’s unpaid interest, a steam from the bank to the owner of the bank opens and the borrowers collateral is streamed out to pay the interest until the stream is reopened or the funds are repaid in full.

Find the REXBank contract here: https://github.com/Ricochet-Exchange/ricochet-protocol/blob/main/contracts/Bank.sol

**Comment by sunnyjaycer** [comment]
I'll take this 🙋🏾‍♂️

**Comment by sunnyjaycer** [comment]
Hey @mikeghen , shouldn't it be: 

Borrow $1000 at 12% APR
Borrower streams **$10**/month (or $120/year) in interest until they repay

1000 * (1+12%) = $1120 -> $120 in interest over the year

**Comment by sunnyjaycer** [comment]
Hey @mikeghen, changed my mind. Will be resuming work on this later this week.
