### ISSUE TITLE
Upgrade to Tellor Flex

### ISSUE THREAD

**Issue by josealonso** [Ricochet-Exchange/ricochet-protocol#81]
Updated by @mikeghen:

There’s a new version of the Tellor Oracle contract on Polygon. This task is to integrate with the latest version of Tellor Oracle contract. The work for this is already done by the Tellor team, we just need to verify it works and then adjust the REX Keepers to report the prices we need. |

**Comment by tkernell** [comment]
This PR https://github.com/Ricochet-Exchange/ricochet-protocol/pull/86 replaces #80.
