### ISSUE TITLE
Lock `node` version

### ISSUE THREAD

**Issue by zhyd1997** [Ricochet-Exchange/ricochet-protocol#83]
After talking with @josealonso, we should lock the `node` version to `16`:
https://discord.com/channels/862796510604296263/950407440455827526/950576938412568707

but there are many `16` minor versions, so for more stability and compatibility, I think we should use **specified** node version like `16.6.1` or else works for you instead of just using `16.x`.

What do you think of this? @mikeghen 

I will submit a PR.

**Comment by zhyd1997** [comment]
Seems that `usingtellor` limits the `node` version lock.
https://github.com/Ricochet-Exchange/ricochet-protocol/blob/21bef8c63beb3f3cb5ac91b0247a946209159913/package.json#L53

<img width="677" alt="npm i" src="https://user-images.githubusercontent.com/31362988/157233112-f5ef6354-e6ef-45b0-8f87-e72497c43f56.png">
<img width="677" alt="npm ls contract" src="https://user-images.githubusercontent.com/31362988/157233144-7db97e79-ba6d-4444-b392-638fff933f71.png">

**Comment by zhyd1997** [comment]
In other words, we have no need to lock `node` version for `hardhat`?
https://hardhat.org/reference/stability-guarantees.html#node-js-versions-support

**Comment by mikeghen** [comment]
@zhyd1997, I actually think we can get rid of usingtellor

**Comment by mikeghen** [comment]
Yes, I like this

**Comment by zhyd1997** [comment]
Okay, waiting for codebase change.

**Comment by zhyd1997** [comment]
On the road:
https://github.com/tellor-io/usingtellor/pull/64

**Comment by mikeghen** [comment]
@zhyd1997, is this ready to merge?

**Comment by zhyd1997** [comment]
@mikeghen waiting for tellor publish new version npm package.
