### ISSUE TITLE
Use `updatePrices()` method instead of `updatePrice(token)`

### ISSUE THREAD

**Issue by mikeghen** [Ricochet-Exchange/ricochet-protocol#89]
There's a method to update both prices at once called `updatePrices()`. This issue is to update the `ricochet_distribute_v2` workflow to use that method.

Both methods are supported for more advanced keeper oracle updates, i.e. updating 1 of the 2 prices separately

**Comment by josealonso** [comment]
In the `REXTwoWayMarket` test files only `updatePrices()` is called. What Solidity file are you referring to, @mikeghen ?

**Comment by josealonso** [comment]
Are you talking about the keepers ? This belongs to the `keepers` repository, @mikeghen, this one is `ricochet-protocol`

**Comment by mikeghen** [comment]
Closed, this is in the wrong repo
