### ISSUE TITLE
`REXOneWayMarket` Tests and Migration to Typescript

### ISSUE THREAD

**Issue by mikeghen** [Ricochet-Exchange/ricochet-protocol#9]
This issue is about testing and debugging the `REXOneWayMarket` contract. The contract is mostly code complete with perhaps a few things missing. The code is untested and needs to be both tested and then anything not working should be debugged.

**Comment by vaibhavgeek** [comment]
@mikeghen , can you assign this to me please?

**Comment by vaibhavgeek** [comment]
RexMarket is a abstract contract so tests for both REXMarket and REXOneWayMarket would be covered in a single test file. 

 Most of the functions listed below have been implemented in javascript [here](https://github.com/Ricochet-Exchange/ricochet-protocol/blob/main/test/REXOneWayMarket.test.js). The plan is to convert them to typescript and add more functions (listed below). Please feel free to add more to the list, there are chances that I might have missed something. 

- Deploy REXOneWayMarket contract and check all the getter functions of REXMarket holds true.
- Check if all the functions with `onlyOwner` can be allowed owner and not any other address.
- Initialise market, add primary output pool, add secondary output pool and check via getter functions
- Approve token spending and check if they are unlimited
- Get, Delete and update stream and check for corresponding values
- Trigger distribution and check new balances for tokens in output pools
- If App is jailed then it should allow for emergency stop of streams
- If no input stream , then drain tokens to owners
- Check uninvested amount is returned back to the streamer
- Check token price via API and update it on contract and make sure they match.

**Comment by josealonso** [comment]
I'm writing the tests for `REXTwoWayMarket`, based on the template provided by @vaibhavgeek

**Comment by vaibhavgeek** [comment]
This uses typescript and superfluid sdk-core to test the changes, as of now on running 

`npx hardhat test test/rexOneWayMarket.test.ts` 

Three tests would pass, two fail out of the five written as the contract is still being written and formatted. This code can be replicated for RexTwoMarket as well @josealonso  and functions need to be added on the ones written already.

**Comment by josealonso** [comment]
@vaibhavgeek and I are on it.

**Comment by josealonso** [comment]
@vaibhavgeek is doing the whole task.

**Comment by josealonso** [comment]
@vaibhavgeek, I think you finished this task, but it can't be merged yet. Do we have to wait until v.2 contracts are deployed, then ?

**Comment by josealonso** [comment]
The `REXOneWayMarket` contract is not currently used, so this issue might have to be closed. @mikeghen

**Comment by mikeghen** [comment]
All set with this, nice work @josealonso
