### ISSUE TITLE
Use the V1 contracts 

### ISSUE THREAD

**Issue by josealonso** [Ricochet-Exchange/ricochet-protocol#92]
The app currently uses the V2 contracts, but some of them have jail errors. This is not strange, since these contracts are very complex and a lot of testing has to be done to try to prevent all these errors. Building all these tests will take a big amount of time. Therefore, going back to the V1 contracts until the V2 ones are ready seems a plausible solution.

**Comment by josealonso** [comment]
Version 1.3 of the contracts is on this repo ---> https://github.com/Ricochet-Exchange/ricochet/tree/main/01-Contracts/contracts. There are *only* three files, with no internal swaps or something overly complex.

**Comment by josealonso** [comment]
I still think this option could be explored, especially because @rashtrakoff's code for a similar project uses a Factory and his code coverage is very high. But noone seems to care.

**Comment by mikeghen** [comment]
Reopen this in the v1 repo  ricochet-exchange/ricochet if you want to pursue this
