### ISSUE TITLE
Reduce Contract Size

### ISSUE THREAD

**Issue by mikeghen** [Ricochet-Exchange/ricochet-protocol#95]
REX Market contracts are pushing the limits allowed for deployed contracts ~24.6 KB. This task is to reduce the contract sizes. This is required so that other features can be implemented. Right now the contracts are packed super tight.

Some guidance from a conversation I had with a dev:

Mike, [Apr 28, 2022 at 9:48:58 AM]:
1. The focus should be on REXMarket.sol, that contract gets extended by the other contracts. So that is the target. I should have made a REXMarketStorage.sol and REXMarketHelper.sol, and maybe also make a SuperfluidHelper.sol, that was the idea I had to split things into libraries. 
2. It's a contract size issue, the contracts are 24KB so there's no room for more functionality at this point. So I need some help shrinking up the contract sizes using libraries so I can start adding some more functionality

Mike, [Apr 28, 2022 at 10:23:49 AM]:
As an example, you can see in the version 1 of the Ricochet contracts there was a StreamExchangeHelper and SteamExchangeStorage lib: https://github.com/Ricochet-Exchange/ricochet/tree/main/01-Contracts/contracts

And in this project, you can see there's an SFHelper.sol (i.e. SuperfluidHelper) library: https://github.com/DAM-Protocol/SIP-Contracts/blob/master/contracts/Common/SFHelper.sol

So just some guidance which I hope helps would be, to reduce the REXMarket contract size, REXMarket is abstract so use REXTwoWayMarket.sol to check the size, do the reduction by creating 3 libs:
- REXMarketStorage.sol
- REXMarketHelper.sol
- SuperfluidHelper.sol
I hope that guidance is helpful, I'm not 100% sure this is the best architecture, but based on the examples I shared, I think this would be the way to do it

**Comment by mikeghen** [comment]
Another way to save some space is to use the RexSuperSwap contract in the `_swap` method since that contract handles upgrade/downgrade

**Comment by josealonso** [comment]
@mikeghen, did you break up the contract in a helper one and a storage one ?
