### ISSUE TITLE
Keeper Incentives

### ISSUE THREAD

**Issue by mikeghen** [Ricochet-Exchange/ricochet-protocol#96]
Currently, keepers are paid a monthly stipend. Unfortunately, this isn’t a good incentive since keepers are getting paid regardless of their reliability. This task is to implement a pay-per-performance similar to other projects. Keepers should be paid a portion of the fees collected as part of the distribution method.

This will probably be tricky to do with IDA shares so I would suggest that this is implemented in a way that's similar to the PIC system in Superfluid sentinels. That is, the keeper that wants to earn the reward stakes RIC tokens to be the PIC, very much like King of the hill. That keeper who staked the most RIC is entitled to all the keeper rewards. If the keeper that's staked doesn't keep within a certain time period, another keeper can keep and their reward is taken from the stake of the main keeper.

**Comment by shreyaspapi** [comment]
Can we close this one? As distributions are managed by Gelato I don't think we need this anymore.
